[program:repo-watch-api]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/repo-watch-api/current/artisan serve --host=127.0.0.1 --port=8012
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/repo-watch-api/shared/storage/logs/server.log
stopwaitsecs=30

[program:repo-watch-api-worker]
command=php /var/www/repo-watch-api/current/artisan queue:work --sleep=1 --tries=3 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/repo-watch-api/shared/storage/logs/worker.log
stopwaitsecs=3600
